/**
 * Build-time generator for the "Love Revealed" wordmark.
 *
 * Loads the Oooh Baby font with opentype.js and extracts PER-GLYPH outlines for
 * the hero text, writing them as STATIC SVG path data to `lib/traced-hero.ts`.
 * The client renders those static paths only — opentype.js and the .ttf are
 * never shipped to or parsed on the browser (SPEC §13 performance priority).
 * Splitting per glyph (not per subpath) keeps each letter's counters/holes
 * together, so the UI can reveal the wordmark one solid letter at a time.
 *
 * Run: `bun scripts/gen-traced-hero.ts`
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "opentype.js";

const HERO_TEXT = "Love Revealed";
/** Design font-size in path units; the viewBox rides on these coordinates. */
const FONT_SIZE = 100;
/** Padding around the glyph bounds so nothing clips at the edges. */
const PAD = 10;
/** Decimal precision of the emitted path data (smaller = fewer bytes). */
const PRECISION = 2;
const SCALE = 10 ** PRECISION;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontPath = resolve(root, "public/fonts/OoohBaby-Regular.ttf");
const outPath = resolve(root, "lib/traced-hero.ts");

const file = readFileSync(fontPath);
const buffer = file.buffer.slice(
  file.byteOffset,
  file.byteOffset + file.byteLength,
);
const font = parse(buffer);

// opentype.js 2.0 `toPathData` emits NaN coordinates for this font, so serialize
// the (clean) command list ourselves, rounding to PRECISION decimals. One <path>
// per glyph; whitespace glyphs have no contours, so drop the empties to keep the
// letter-by-letter reveal evenly staggered.
const glyphs = font
  .getPaths(HERO_TEXT, 0, 0, FONT_SIZE)
  .map((p) => {
    const parts: string[] = [];
    for (const c of p.commands) {
      if (c.type === "Z") {
        parts.push("Z");
        continue;
      }
      const coords =
        c.type === "M" || c.type === "L"
          ? [c.x, c.y]
          : c.type === "Q"
            ? [c.x1, c.y1, c.x, c.y]
            : [c.x1, c.y1, c.x2, c.y2, c.x, c.y];
      parts.push(
        c.type + coords.map((n) => Math.round(n * SCALE) / SCALE).join(" "),
      );
    }
    return parts.join("");
  })
  .filter((d) => d.length > 0);

// viewBox from the combined outline so it frames the whole wordmark.
const bb = font.getPath(HERO_TEXT, 0, 0, FONT_SIZE).getBoundingBox();
const [x, y, width, height] = [
  bb.x1 - PAD,
  bb.y1 - PAD,
  bb.x2 - bb.x1 + PAD * 2,
  bb.y2 - bb.y1 + PAD * 2,
].map((n) => Math.round(n * 100) / 100);
const viewBox = `${x} ${y} ${width} ${height}`;

const banner = `// GENERATED by scripts/gen-traced-hero.ts — DO NOT EDIT BY HAND.
// Per-glyph outlines of the "${HERO_TEXT}" wordmark in the Oooh Baby display
// face, pre-extracted at build time so the client never loads opentype.js or
// the font. One entry per visible letter, in reading order.
`;

const contents = `${banner}
export interface TracedGlyph {
  /** SVG path data, one string per visible letter (reading order). */
  glyphs: string[];
  /** viewBox framing the whole wordmark. */
  viewBox: string;
  /** Intrinsic width of the viewBox (for aspect-ratio sizing). */
  width: number;
  /** Intrinsic height of the viewBox. */
  height: number;
  /** The text this wordmark spells. */
  text: string;
}

export const TRACED_HERO: TracedGlyph = {
  glyphs: ${JSON.stringify(glyphs)},
  viewBox: ${JSON.stringify(viewBox)},
  width: ${width},
  height: ${height},
  text: ${JSON.stringify(HERO_TEXT)},
};
`;

writeFileSync(outPath, contents);
console.log(
  `traced-hero: wrote ${outPath}\n  text="${HERO_TEXT}" glyphs=${glyphs.length} viewBox="${viewBox}"`,
);
