/**
 * Build-time generator for the traced "Love Revealed" wordmark.
 *
 * Loads the Oooh Baby font with opentype.js, extracts the glyph outline for the
 * hero text, and writes it as STATIC SVG path data to `lib/traced-hero.ts`.
 * The client renders that static path only — opentype.js and the .ttf are never
 * shipped to or parsed on the browser (SPEC §13 performance priority).
 *
 * Run: `bun scripts/gen-traced-hero.ts`
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "opentype.js";

const HERO_TEXT = "Love Revealed";
/** Design font-size in path units; the viewBox rides on these coordinates. */
const FONT_SIZE = 100;
/** Padding around the glyph bounds so the stroke never clips at the edges. */
const PAD = 10;
/** Decimal precision of the emitted path data (smaller = fewer bytes). */
const PRECISION = 2;

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const fontPath = resolve(root, "public/fonts/OoohBaby-Regular.ttf");
const outPath = resolve(root, "lib/traced-hero.ts");

const file = readFileSync(fontPath);
const buffer = file.buffer.slice(
  file.byteOffset,
  file.byteOffset + file.byteLength,
);
const font = parse(buffer);

const path = font.getPath(HERO_TEXT, 0, 0, FONT_SIZE);
// opentype.js 2.0 `toPathData` emits NaN coordinates for this font, so serialize
// the (clean) command list ourselves, rounding to PRECISION decimals.
const SCALE = 10 ** PRECISION;
const parts: string[] = [];
for (const c of path.commands) {
  if (c.type === "Z") {
    parts.push("Z");
    continue;
  }
  const coords =
    c.type === "M" || c.type === "L"
      ? [c.x, c.y]
      : c.type === "Q"
        ? [c.x1, c.y1, c.x, c.y]
        : [c.x1, c.y1, c.x2, c.y2, c.x, c.y];
  parts.push(
    c.type + coords.map((n) => Math.round(n * SCALE) / SCALE).join(" "),
  );
}
const d = parts.join("");
const bb = path.getBoundingBox();

const [x, y, width, height] = [
  bb.x1 - PAD,
  bb.y1 - PAD,
  bb.x2 - bb.x1 + PAD * 2,
  bb.y2 - bb.y1 + PAD * 2,
].map((n) => Math.round(n * 100) / 100);
const viewBox = `${x} ${y} ${width} ${height}`;

const banner = `// GENERATED by scripts/gen-traced-hero.ts — DO NOT EDIT BY HAND.
// Static outline of the "${HERO_TEXT}" wordmark in the Oooh Baby display face,
// pre-extracted at build time so the client never loads opentype.js or the font.
`;

const contents = `${banner}
export interface TracedGlyph {
  /** SVG path data for the wordmark outline. */
  d: string;
  /** viewBox matching the path's coordinate space. */
  viewBox: string;
  /** Intrinsic width of the viewBox (for aspect-ratio sizing). */
  width: number;
  /** Intrinsic height of the viewBox. */
  height: number;
  /** The text this glyph path spells. */
  text: string;
}

export const TRACED_HERO: TracedGlyph = {
  d: ${JSON.stringify(d)},
  viewBox: ${JSON.stringify(viewBox)},
  width: ${width},
  height: ${height},
  text: ${JSON.stringify(HERO_TEXT)},
};
`;

writeFileSync(outPath, contents);
console.log(
  `traced-hero: wrote ${outPath}\n  text="${HERO_TEXT}" viewBox="${viewBox}" bytes=${d.length}`,
);
